version: '3'

volumes:
  cache:
  storage:

services:
  cache:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  storage:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: secret-key
    command: server /data --console-address :9001
    volumes:
      - storage:/data
