name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cache:
        image: redis:7
        ports:
          - 6379:6379
      storage:
        image: minio/minio
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: access-key
          MINIO_SECRET_KEY: secret-key
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - run: pip install -e . -r requirements/test.txt
      - run: pytest
        env:
          CACHE_URL: redis://localhost:6379/0
          DEBUG: 1
          STORAGE_URL: http://access-key:secret-key@localhost:9000
