name: test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      cache:
        image: redis:7
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping"
      storage:
        image: minio/minio:edge-cicd
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: access-key
          MINIO_SECRET_KEY: secret-key
        options: --health-cmd "curl http://localhost:9000/minio/health/live"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.8'
      - run: pip install -e . -r requirements/test.txt
      - name: pytest
        run: |
          easypub collectstatic && \
          easypub makebucket && \
          pytest
        env:
          CACHE_URL: redis://0.0.0.0:6379/0
          DEBUG: 1
          STORAGE_URL: http://access-key:secret-key@0.0.0.0:9000
